include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    always_use_package_imports: false
    public_member_api_docs: false
    sort_constructors_first: false

analyzer:
  errors:
    argument_type_not_assignable: ignore # TODO: remove soon
