include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    unawaited_futures: false
    sort_pub_dependencies: false
    public_member_api_docs: false
    sort_constructors_first: false
    omit_local_variable_types: false
    always_use_package_imports: false
    avoid_bool_literals_in_conditional_expressions: false
