name: bithabit
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

isar_version: &isar_version 3.1.0 # define the version to be used

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # core
  provider: ^6.0.5
  flex_color_scheme: ^7.0.5
  # utils
  fl_chart: ^0.62.0
  url_launcher: ^6.1.11
  file_picker: ^5.3.0
  package_info_plus: ^4.0.0
  # view
  recase: ^4.1.0
  confetti: ^0.7.0
  icons_plus: ^4.0.0
  achievement_view: ^1.0.0
  custom_navigation_bar: ^0.8.2
  flutter_advanced_segment: ^3.0.2
  # audio
  audioplayers: ^4.0.1
  # dev
  device_preview: ^1.1.0

  # Database
  isar: *isar_version
  isar_flutter_libs: *isar_version # contains Isar Core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: *isar_version
  very_good_analysis: ^4.0.0+1
  build_runner: any

flutter:
  # The following line ensures that the Material Iconss font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
