// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3tWpMhrJTN6N1sX3zWLBVECOyF9vYxlw',
    appId: '1:1061987817719:web:290b18d637f54031ab1bf2',
    messagingSenderId: '1061987817719',
    projectId: 'bithabit-app',
    authDomain: 'bithabit-app.firebaseapp.com',
    storageBucket: 'bithabit-app.appspot.com',
    measurementId: 'G-C8PGQ3S262',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXvhTk-dsZDOn864ECCGZgbzej45cqBzg',
    appId: '1:1061987817719:android:98bbc8ed44f88127ab1bf2',
    messagingSenderId: '1061987817719',
    projectId: 'bithabit-app',
    storageBucket: 'bithabit-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIxRNx6MZColdTSblBQBFll38RD9eype4',
    appId: '1:1061987817719:ios:53a2228284865ef9ab1bf2',
    messagingSenderId: '1061987817719',
    projectId: 'bithabit-app',
    storageBucket: 'bithabit-app.appspot.com',
    iosBundleId: 'com.luxinfity.bithabit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIxRNx6MZColdTSblBQBFll38RD9eype4',
    appId: '1:1061987817719:ios:53a2228284865ef9ab1bf2',
    messagingSenderId: '1061987817719',
    projectId: 'bithabit-app',
    storageBucket: 'bithabit-app.appspot.com',
    iosBundleId: 'com.luxinfity.bithabit',
  );
}
